### ISSUE TITLE
problems with buddypress 7.3.0 and learndash 3.4.0.8

### ISSUE THREAD

**Issue by cib009** [uday-kokitkar/extended-learndash-notifications#1]
Hello @uday-kokitkar  I tried this library with buddypress 7.3.0 and learndash 3.4.0.8 and seems no work.

If I put the option on "buddypress" nothing ocurrs but I put option "email + buddypress" the email was sended but I can't see it in the notifies page of buddypress. 

To give more info, the private messaging was activated.

How I can debug this to view more errors? 

thanks!

**Comment by uday-kokitkar** [comment]
Thanks for reporting an issue @cib009 .

I see the changes in the latest LearnDash Notifications plugin. I'm using the hook `learndash_notifications_send_email` to trigger a BuddyPress message but I see now that LD's code is not executing that hook. I don't see any deprecated functions list from LearnDash either.

The following code is responsible to send emails but LD has not added a preferable hook to extend the functionality.

![image](https://user-images.githubusercontent.com/61972002/118427939-f2ae2180-b6eb-11eb-9f33-59f37b412c5d.png)

Anyway, I'm going to dive deep into the code and fix the issue.

**Comment by cib009** [comment]
Hi @uday-kokitkar, thanks a lot for response.

At the moment I tried to modify leandDash notification files to add a new line to trigger a new filter like this:

`				apply_filters( 'learndash_notifications_send_email', $is_send, $email, $model->post->ID );
`

But it's not work for me. Can be a solution?

Thanks a lot!

**Comment by ribeiroeder** [comment]
Hi!

I currently use Learndash + BuddyBoss to provide a members area where they can only take courses. Almost all social networking functionality is purposely disabled.

What I can see is that the notifications function would still be very useful if I left it working. I don't want to send him an email every time he completes a course or quizz, I just want to notify him internally.

This demand for a members-only course area has been highly sought after, and the BuddyBoos platform has commercially exploited the proposal along with a major integration partnership with LearnDash.

Amazingly, there is no free or paid solution that integrates LearnDash notifications with BuddyBoss private notifications.

Evaluating your plugin, it seems to me to be the closest we have to achieving this functionality, and if it works correctly, it could be paid for! Since the BuddyBoss community is a "premium fork" of BuddyPress.

As an example, I can mention the GamiPress plugin which has a premium addon that extends the notification functionality to BuddyBoss.

If you develop something, I'll be the first to buy and try it! Please assess this market need, I believe it would be incredibly popular.

**Comment by ribeiroeder** [comment]
For the record, I tested the plugin with BuddyBoss instead of BuddyPress, but everything worked exactly as @cib009 mentioned.

**Comment by uday-kokitkar** [comment]
Thanks @cib009 



> Hi @uday-kokitkar, thanks a lot for response.
> 
> At the moment I tried to modify leandDash notification files to add a new line to trigger a new filter like this:
> 
> ` apply_filters( 'learndash_notifications_send_email', $is_send, $email, $model->post->ID ); `
> 
> But it's not work for me. Can be a solution?
> 
> Thanks a lot!

Thanks @cib009 Your solution should work. ~~I added this line in the file `plugins/learndash-notifications/src/trigger.php` at line number 71 and the plugin is working as expected.~~
Please check out the IMPORTANT CHANGE in the readme file [here](https://github.com/uday-kokitkar/extended-learndash-notifications/blob/master/readme.md#configuration).

**Comment by ribeiroeder** [comment]
Great! Working perfectly with this setting. Thanks
